//lib/mockEmployees.ts
import type { Employee } from '@/types/employee';

export const mockEmployees: Employee[] = [
  {
    id: 'emp_001',
    name: 'Sophia Carter',
    email: 'sophia@flowbase.com',
    department: 'HR',
    jobTitle: 'HR Manager',
    joinedDate: '2023-05-01',
    status: 'active',
    userRole: 'admin',
  },
  {
    id: 'emp_002',
    name: 'Emma Wilson',
    email: 'emma@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Frontend Engineer',
    joinedDate: '2024-02-15',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_003',
    name: 'Liam Chen',
    email: 'liam@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Backend Engineer',
    joinedDate: '2023-11-20',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_004',
    name: 'Olivia Brown',
    email: 'olivia@flowbase.com',
    department: 'Design',
    jobTitle: 'UI/UX Designer',
    joinedDate: '2024-01-10',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_005',
    name: 'Noah Patel',
    email: 'noah@flowbase.com',
    department: 'Product',
    jobTitle: 'Product Manager',
    joinedDate: '2023-08-18',
    status: 'inactive',
    userRole: 'employee',
  },
  {
    id: 'emp_006',
    name: 'Ava Martinez',
    email: 'ava@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Full Stack Engineer',
    joinedDate: '2024-03-04',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_007',
    name: 'Ethan Walker',
    email: 'ethan@flowbase.com',
    department: 'Engineering',
    jobTitle: 'QA Engineer',
    joinedDate: '2023-09-12',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_008',
    name: 'Isabella Kim',
    email: 'isabella@flowbase.com',
    department: 'Design',
    jobTitle: 'Product Designer',
    joinedDate: '2024-04-22',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_009',
    name: 'Mason Lee',
    email: 'mason@flowbase.com',
    department: 'Sales',
    jobTitle: 'Account Executive',
    joinedDate: '2023-07-03',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_010',
    name: 'Charlotte Davis',
    email: 'charlotte@flowbase.com',
    department: 'Marketing',
    jobTitle: 'Marketing Specialist',
    joinedDate: '2024-05-13',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_011',
    name: 'James Nguyen',
    email: 'james@flowbase.com',
    department: 'Engineering',
    jobTitle: 'DevOps Engineer',
    joinedDate: '2023-10-09',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_012',
    name: 'Amelia Garcia',
    email: 'amelia@flowbase.com',
    department: 'Customer Support',
    jobTitle: 'Support Specialist',
    joinedDate: '2024-06-17',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_013',
    name: 'Benjamin Hall',
    email: 'benjamin@flowbase.com',
    department: 'Finance',
    jobTitle: 'Finance Manager',
    joinedDate: '2023-06-26',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_014',
    name: 'Mia Clark',
    email: 'mia@flowbase.com',
    department: 'HR',
    jobTitle: 'Recruiter',
    joinedDate: '2024-02-01',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_015',
    name: 'Lucas Robinson',
    email: 'lucas@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Mobile Engineer',
    joinedDate: '2023-12-11',
    status: 'inactive',
    userRole: 'employee',
  },
  {
    id: 'emp_016',
    name: 'Harper Lewis',
    email: 'harper@flowbase.com',
    department: 'Product',
    jobTitle: 'Product Owner',
    joinedDate: '2023-08-07',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_017',
    name: 'Henry Young',
    email: 'henry@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Data Engineer',
    joinedDate: '2024-01-29',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_018',
    name: 'Evelyn Allen',
    email: 'evelyn@flowbase.com',
    department: 'Operations',
    jobTitle: 'Operations Coordinator',
    joinedDate: '2023-11-06',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_019',
    name: 'Alexander Wright',
    email: 'alexander@flowbase.com',
    department: 'Sales',
    jobTitle: 'Sales Manager',
    joinedDate: '2023-05-15',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_020',
    name: 'Ella Hernandez',
    email: 'ella@flowbase.com',
    department: 'Marketing',
    jobTitle: 'Content Strategist',
    joinedDate: '2024-03-18',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_021',
    name: 'Daniel King',
    email: 'daniel@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Security Engineer',
    joinedDate: '2023-09-25',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_022',
    name: 'Scarlett Scott',
    email: 'scarlett@flowbase.com',
    department: 'Customer Support',
    jobTitle: 'Customer Success Manager',
    joinedDate: '2024-04-08',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_023',
    name: 'Matthew Green',
    email: 'matthew@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Software Engineer',
    joinedDate: '2024-05-27',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_024',
    name: 'Grace Adams',
    email: 'grace@flowbase.com',
    department: 'Design',
    jobTitle: 'Visual Designer',
    joinedDate: '2023-10-30',
    status: 'inactive',
    userRole: 'employee',
  },
  {
    id: 'emp_025',
    name: 'Joseph Baker',
    email: 'joseph@flowbase.com',
    department: 'Finance',
    jobTitle: 'Financial Analyst',
    joinedDate: '2024-01-22',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_026',
    name: 'Chloe Nelson',
    email: 'chloe@flowbase.com',
    department: 'Operations',
    jobTitle: 'Office Manager',
    joinedDate: '2023-07-24',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_027',
    name: 'David Campbell',
    email: 'david@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Tech Lead',
    joinedDate: '2023-04-17',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_028',
    name: 'Aria Mitchell',
    email: 'aria@flowbase.com',
    department: 'Product',
    jobTitle: 'Business Analyst',
    joinedDate: '2024-06-03',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_029',
    name: 'Sebastian Perez',
    email: 'sebastian@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Backend Engineer',
    joinedDate: '2023-12-04',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_030',
    name: 'Lily Turner',
    email: 'lily@flowbase.com',
    department: 'HR',
    jobTitle: 'People Operations Specialist',
    joinedDate: '2024-02-26',
    status: 'active',
    userRole: 'employee',
  },
];