import type { Employee } from '@/types/employee';

export const mockEmployees: Employee[] = [
  {
    id: 'emp_001',
    name: 'Sophia Carter',
    email: 'sophia@flowbase.com',
    department: 'HR',
    jobTitle: 'HR Manager',
    joinedDate: '2023-05-01',
    status: 'active',
    userRole: 'admin',
  },
  {
    id: 'emp_002',
    name: 'Emma Wilson',
    email: 'emma@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Frontend Engineer',
    joinedDate: '2024-02-15',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_003',
    name: 'Liam Chen',
    email: 'liam@flowbase.com',
    department: 'Engineering',
    jobTitle: 'Backend Engineer',
    joinedDate: '2023-11-20',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_004',
    name: 'Olivia Brown',
    email: 'olivia@flowbase.com',
    department: 'Design',
    jobTitle: 'UI/UX Designer',
    joinedDate: '2024-01-10',
    status: 'active',
    userRole: 'employee',
  },
  {
    id: 'emp_005',
    name: 'Noah Patel',
    email: 'noah@flowbase.com',
    department: 'Product',
    jobTitle: 'Product Manager',
    joinedDate: '2023-08-18',
    status: 'inactive',
    userRole: 'employee',
  },
];